### PR TITLE
Move producer invite to a nice modal; sanitize a little

### PR DESCRIPTION
**Pull request by liamdanger**
would you look at that

### CODE REVIEW

**Comment by phildini** [comment]
Can we make it clear it's email _or_ phone number? Right now the form will fail if you put in both.

**Comment by liamdanger** [comment]
> Can we make it clear it's email _or_ phone number? Right now the form will fail if you put in both.

It does??? I've been putting in both and getting valid responses

**Comment by phildini** [comment]
What kind of valid responses? Have you been getting an email and a text?

**Comment by liamdanger** [comment]
Now workin'! I'm not putting too much validation on this for now—if you give it both an email and a phone number it'll use the email; If you give it an oddly formatted phone number it'll try to sanitize it.

Screenshot 2020-04-28 16 20 12

**Pull request merged**
